services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - GITLAB_PERSONAL_ACCESS_TOKEN=${GITLAB_PERSONAL_ACCESS_TOKEN}
      - GITLAB_API_URL=${GITLAB_API_URL}