apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-operator
  namespace: agent-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-operator
  template:
    metadata:
      labels:
        app: agent-operator
    spec:
      serviceAccountName: agent-operator
      containers:
      - name: operator
        image: your-dockerhub/agent-operator:1.0   # Jenkins에서 태그 갱신
        ports:
        - containerPort: 8002                       # agent-operator가 실제 듣는 포트
        readinessProbe:                            # Ready 체크
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:                             # Live 체크
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
