apiVersion: v1
kind: Service
metadata:
  name: agent-operator
  namespace: agent-env
spec:
  type: ClusterIP
  selector:
    app: agent-operator
  ports:
  - port: 80
    targetPort: 8002
    nodePort: 30082
